name: cook_county_school_analysis

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pandas
  - numpy
  - geopandas
  - shapely
  - pyproj
  - rtree
  - matplotlib
  - contextily
  - geopy
  - requests
  - streamlit
  - plotly
  - scipy
